### PR TITLE
Bring back hyper with proxy support

### LINKED ISSUE #509: Reintegrate hyper
@sfackler has updated [native-tls to use new schannel bindings](https://github.com/sfackler/rust-native-tls/blob/master/Cargo.toml#L16-L17). Let's add support back for hyper, alongside curl, switchable at runtime I think.

This will involve updating the rustup-utils crate to have two different download functions, the existing one that uses curl, and the new one that uses hyper and native-tls. Look at the revert of 5fc6377aa6d6fa61d2f90ad2e8f67e4a68b83623 to figure out how to write hyper + native-tls.

If the `RUSTUP_USE_HYPER` env var is set then use hyper, otherwise use curl.

cc @seanmonstar

### PR DESCRIPTION
**Pull request by inejge**
Reintegrate hyper support and make it selectable at runtime by setting the environment. Add proxy support to downloads handled by hyper (also activated by setting the environment.)

Fixes #509

### CODE REVIEW

**Comment by brson** [comment]
I retried just to see what happens.

**Comment by alexcrichton** [comment]
I believe the CI error means that Cargo.lock may not be up to date and the CI builders are trying to modify the readonly copy. Perhaps a `cargo build` locally and being sure to check in that updated Cargo.lock would work?

**Comment by inejge** [comment]
> I believe the CI error means that Cargo.lock may not be up to date and the CI builders are trying to modify the readonly copy.

Exactly right. Travis builds are now passing, thanks and sorry for the noise.

**Comment by brson** [comment]
Thanks @inejge!

**Pull request merged**
