### PR TITLE
Chain ErrorKind::HttpStatus(404) to Download404

### LINKED ISSUE #487: historical nightlies get 404
In trying to install a history nightly, like:

```
> rustup update nightly-2016-02-11
```
I am getting a 404.  I looked in the directory to confirm that the build failed that day, but it appears to have succeeded:

https://static.rust-lang.org/dist/2016-02-11/

But the particular file rustup is looking for isn't there:

```
error: could not download file from 'https://static.rust-lang.org/dist/2016-02-11/channel-rust-nightly.toml.sha256' to '/Users/jturner/.multirust/tmp/746z4ulh9xnbk95b_file
info: caused by: http request returned an unsuccessful status code: 404
```

I had a quick chat with @alexcrichton, and mentioned that this may be a possible bug where rustup doesn't support the earlier build artifacts, yet.

### LINKED ISSUE #502: Can’t install Rust 1.7
```sh
$ rustup update 1.7.0
info: syncing channel updates for '1.7.0-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-1.7.0.toml.sha256' to '/home/simon/tmp/rustup/tmp/t8x2esx8afoxnd_y_file
info: caused by: http request returned an unsuccessful status code: 404

### PR DESCRIPTION
**Pull request by cuviper**
Rust pre-1.8.0 didn't have any manifests, so this leads to status 404.
Only error `CURLE_FILE_COULDNT_READ_FILE` was mapping to `Download404`
though, so a "successful" status 404 was causing rustup to give up on
old versions entirely.  Now status 404 is mapped correctly too, and the
manifest fallbacks work correctly.

Fixes #487.
Fixes #502.

### CODE REVIEW

**Comment by cuviper** [comment]
I manually tested that I could install nightly-2016-02-11 per #487 and all the way from 1.7.0 to 1.0.0 for #502.  It wasn't clear to me how to add mocked test cases for these though.  I'd appreciate guidance.

**Comment by alexcrichton** [comment]
Oh dear sorry about that! Looks good to me!

**Comment by brson** [comment]
So awesome. Thanks!

**Comment by brson** [comment]
I'm surprised this wasn't represented in the test suite....

**Pull request merged**
