### PR TITLE
'default' and 'update' heuristics for bare triples

### PR DESCRIPTION
**Pull request by inejge**
[For issue #411]

[Whoops, I started working on this before @moosingin3space left his/her comment. Here goes anyway, sorry if it led to wasted effort.]

This patch lets you use any recognizable target triple with __default__ or __update__. The code will scan all installed toolchains matching the given (partial) triple and offer the user to choose one, or, if there is just one found, to confirm its use. If the command is __default__, the current default toolchain is not included in the list of candidates. The user _must_ choose or confirm the inferred choice; there is no automatic operation. An empty list of candidates is an error. So is not choosing/confirming an offer.

### CODE REVIEW

**Comment by brson** [comment]
Thanks @inejge!

I see that your logic is not quite the same as what I suggested on the issue. From my reading, for both the 'default' and 'update' cases this considers all installed toolchains with a matching triple to be candidates.

I think the logic is right for the 'update' case but needs to be different for 'default': the main reason I expect people to typo this when running 'rustup default' is because they are switching their host platform. So e.g. I start off on `nightly-x86_64-pc-windows-gnu` but want to be on `nightly-x86_64-pc-windows-msvc` so I type `rustup default x86_64-pc-windows-msvc`. If that is the most likely scenario, then we can assume they meant `nightly-x86_64-pc-windows-msvc` and suggest that. The logic for this would be: read the current default and pull out the channel name; prepend that channel name to the specified triple to get the suggested triple.

I'm also not sure I want to automatically use the channel name, nor prompt for it, though I can see why one might, and I can see why that's consistent with other areas of rustup that try to just 'do the right thing', notably the command synonyms. I've previously imagined printing out an error suggestion but forcing the user to type it correctly. Have to think about it some.

**Comment by inejge** [comment]
> I think the logic is right for the 'update' case but needs to be different for 'default': the main reason I expect people to typo this when running 'rustup default' is because they are switching their host platform.

Oh, I see -- I misunderstood the example in the original comment on the issue. I'll change the logic for 'default' accordingly, just let me know whether you think that rustup should prompt for a toolchain name or error out.

**Comment by inejge** [comment]
Here's a version of the patch which implements the 'default' logic as it should have in the first place, and terminates with an error in all cases. The triple provided to the subcommand doesn't have to be complete, i.e., it should be possible to enter something like `rustup default msvc` and get switched to `nightly-x86_64-pc-windows-msvc`.

**Comment by brson** [comment]
Thanks @inejge! I'm so sorry I've been slow to respond to this.

**Pull request merged**
