### PR TITLE
Fallback to old download methods if server returns 403

### LINKED ISSUE #452: 0.1.11 fails to install new toolchain "rustup toolchain install 1.6.0"
I am receiving this error on x86_64 linux:

```
+ rustup toolchain install 1.6.0-x86_64-unknown-linux-gnu
info: syncing channel updates for '1.6.0-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-1.6.0.toml.sha256' to '/home/vagrant/.multirust/tmp/sszoa55jy97dkvg7_file
info: caused by: http request returned an unsuccessful status code: 404
```

I assume the channel listing is only for 1.8.0 (since that's the only fixed version with that toml file) but it is overeager to use it on versions lower than 1.8.0?

### PR DESCRIPTION
**Pull request by brson**
Fixes #452 

Can't be tested because no network tests.

r? @alexcrichton

### CODE REVIEW

**Comment by est31** [comment]
Nice to see a fix being proposed so fast :)

**Comment by jethrogb** [comment]
Why don't you just test for all 400 codes?

**Comment by brson** [comment]
@jethrogb That sounds good to me if you want to submit a patch.

**Comment by est31** [comment]
Can there be a new release?

**Comment by masklinn** [comment]
@brson since server changes have already failed rustup.sh several time, wouldn't it be possible and simpler to generate the relevant manifests for older releases (at least the "release" channels anyway) and avoid the fallback?

**Comment by brson** [comment]
@est31 I'm working on getting a new release out.

@masklinn That approach is possible, yes. It hasn't seemed worth it since this is also simple and the code already exists.

**Pull request merged**
