### PR TITLE
Update to error-chain 0.5.0 to allow optional backtrace. #591

### PR DESCRIPTION
**Pull request by squidpickles**
Thought I'd give this a try. No test failures, and it does seem to short-circuit a bunch of system calls with `RUST_BACKTRACE=0`.

### CODE REVIEW

**Comment by squidpickles** [comment]
This is a fix for #591 
Not sure about the build failures. Tests passed locally on Mac and Linux, but I don't have access to a Windows box to debug on. Is this likely a related issue?

**Comment by brson** [comment]
@squidpickles Awesome! This looks great.

The linux failure is because on the bots `cargo build` is causing `Cargo.lock` to be updated, which is considered an error. And I've verified that when I build locally the lockfile also changes. Can you try locally and see if you get the same result, and if so update the lockfile.

Since the build on travis is pinned to nightly-2016-08-10 you might want to try running `rustup override set nightly-2016-08-10` to make sure you've got the same configuration.

The windows failure looks spurious.

Thanks!

**Comment by squidpickles** [comment]
Looks like the `Cargo.lock` update fixed that problem. And, I've got the nightly running in that directory.  Thanks for the help with my help.

**Comment by brson** [comment]
Thank you again. Sorry for leaving this for so long 😧

**Pull request merged**
