### PR TITLE
Detect ARMv7 CPUs without NEON extensions and treat as ARMv6

### PR DESCRIPTION
**Pull request by sourcefrog**
Fixes rust-lang-nursery/rustup.rs/issues/587

### CODE REVIEW

**Comment by sourcefrog** [comment]
NB I don't have any other ARM machines on which I could test this.

**Comment by sourcefrog** [comment]
AppVeyor failure seems like an unrelated network error

https://ci.appveyor.com/project/brson/rustup-rs/build/1.0.401/job/t8lswqjhwcxg3020

**Comment by brson** [comment]
Thanks for the investigation and the patch @sourcefrog!

@alexcrichton and @japaric what do you think of this? Seems like something's wrong with our target defs.

**Comment by sourcefrog** [comment]
Hi brson, are you suggesting maybe you instead want to change the ARMv7 build to work without NEON?  That would be another option.  Or, you could have a separate build for ARMv7+NEON vs without. 

I don't know how much of a boost use of NEON gives to Rust performance, or how common CPUs with and without it are.

**Comment by alexcrichton** [comment]
This seems like a fine patch to merge for now at least (to fix the target detection). I feel like any decision we make on the ARM target we'll eventually get wrong (unless we ship everyone ARMv5 compatible code), so I'm not sure if it's a strong indicator to change the target just yet.

**Comment by brson** [comment]
@sourcefrog oh I wasn't suggesting anything in particular. Getting toolchains to support the wide variety of arm configs is difficult and I just wanted confirmation from folks who are more familiar. Thanks again.

**Comment by japaric** [comment]
For the record: the topic of Scaleway, ARMv7 and NEON has come up before in the [users](https://users.rust-lang.org/t/rust-on-armv7l-with-no-neon-support/6037/8) forum. The TL;DR is:

- The common case is ARMv7 *with* NEON support. Scaleway seems to be an outlier here.
- If you have an ARMv7 processor *without* NEON, you should use the `arm-unknown-linux-gnueabihf` target (what this PR does!) because there's not much difference (codegen wise) between that target and the (non existent) `armv7-unknown-linux-gnueabihf` with NEON disabled.

**Pull request merged**
